root: ./

redirects:
  servers/ipmi-password: servers/general.md
  cloud/launch-instance-api: on-demand-cloud/cloud-api.md
  windows/msinfo32-gather-information: software/windows.md
  cloud/problem-processing-payment-method: on-demand-cloud/billing.md
  linux/recovery-images: software/lambda-stack-and-recovery-images.md
  linux/remove-reinstall-lambda-stack: software/lambda-stack-and-recovery-images.md
  linux/upgrade-ubuntu-and-lambda-stack: software/lambda-stack-and-recovery-images.md
  cloud/use-persistent-storage: on-demand-cloud/file-systems.md
  cloud/file-system-without-instance: on-demand-cloud/file-systems.md
  cloud/rate-limiting: on-demand-cloud/cloud-api.md
  cloud/pause-instance: on-demand-cloud/general.md
  cloud/open-jupyter-notebook: on-demand-cloud/general.md
  linux/create-conda-virtual-environment: software/virtual-environments-and-docker-containers.md
  linux/create-python-virtual-environment: software/virtual-environments-and-docker-containers.md
  servers/user-guides: servers/general.md
  cloud/on-demand-instance-invoicing: on-demand-cloud/billing.md
  cloud/cannot-find-nvidia-cudnn: on-demand-cloud/general.md
  cloud/persistent-storage-billing: on-demand-cloud/billing.md
  windows/system-info-using-dxdiag: software/windows.md
  workstations/upgrade-hardware: workstations/general.md
